Stage 2 and 3
EvaRusinova/email-service pull request #3
Opened 2023-07-19 11:41 UTC by EvaRusinova

Publish and consume a message, via RabbitMQ.

2023-07-19 11:42 UTC, EvaRusinova commented
Connection between user-service and email-service via RabbitMQ is done. 
It works perfectly!
I tested it in this way-registered a user through Swagger, and checked the H2 database, that is new created and used only by email-service. The user credentials are in the DB for a second. 
I added some new dependencies, i commented for what are they added. 
I changed the ports of our applications, so that can run together without disturbing each other(new ports urls down below). 
It was needed to change the paths in email-service(i hope that it's properly maded), because of UserRegistrationEvent (it requires in both of the services to be on the same path).
All of the previos refactoring asked is done.
I also have one question- under the main folder into email-service app, a new auto-generated package appeared, called "generated". I can not open the package, or it doesn have anything on it. I researched, and it can be a result from Gradle, from InteliJ itself or from some plugin/dependency. What we should do with this package? 
Later today or tomorow i'm going to make an email template and implement the sending of an email to a potencial user.
Have a good and COLD day! :) 


Ports:
1. H2 database for USER-SERVICE
	http://localhost:8081/h2-console

2. H2 databse for EMAIL-SERVICE
	http://localhost:8082/h2-console

3.Swagger for USER-SERVICE
	http://localhost:8081/swagger-ui.html

2023-07-19 17:11 UTC, AntoanRusinov commented on build.gradle
> +    implementation 'org.hibernate.validator:hibernate-validator:7.0.1.Final'
and why we need this?

2023-07-19 17:17 UTC, AntoanRusinov commented on build.gradle
> +    // Spring
For this jakarta and hibernate validator, we don't need versions, we can just do something like that: 

// Jakarta Bean Validation API
implementation 'jakarta.validation:jakarta.validation-api'
// Hibernate Validator as the implementation of Jakarta Bean Validation
implementation 'org.hibernate.validator:hibernate-validator


By removing the version numbers, Gradle will use its dependency resolution mechanism to select the appropriate versions based on the dependency constraints and resolution strategy defined in your Gradle project. This way, you can import the dependencies without explicitly specifying the versions. 

but add those dependencies below spring.

2023-07-19 17:17 UTC, AntoanRusinov commented on build.gradle
> +    compileOnly 'org.projectlombok:lombok:1.18.22'
no need of this - delete it

2023-07-19 17:17 UTC, AntoanRusinov commented on build.gradle
> +    id 'io.freefair.lombok' version '6.5.0'
delete this plugin - no need

2023-07-19 17:18 UTC, AntoanRusinov commented on lombok.config
> +config.stopBubbling = true
delete this file - as it says it's generated by the plugin and since we deleted the plugin the file won't be generated anymore

2023-07-19 17:22 UTC, AntoanRusinov commented on src/main/java/com/example/initial/event/UserRegistrationEvent.java
> +@Setter
the setter is not used here, delete it. AllArgsConstructor is not used too. Please, stop adding annotations just for fun 😁 make sure you really need them! 😁

2023-07-19 17:22 UTC, AntoanRusinov commented on src/main/java/com/example/initial/listener/UserRegistrationEventListener.java
> +        User user = User.builder()
use MapStruct mapper here to do the mapping

2023-07-19 17:23 UTC, AntoanRusinov commented on src/main/java/com/example/initial/listener/UserRegistrationEventListener.java
> +        // Handle the user registration event
basically, here you need to send the email, this is all

2023-07-19 17:26 UTC, AntoanRusinov commented on src/main/resources/application.yaml
>  #services:
delete this, please, I forgot it here

2023-07-19 17:30 UTC, AntoanRusinov commented on src/main/java/com/example/initial/config/RabbitMQConfig.java
> +
we need to talk about that class: "Important Eva" thread

2023-07-19 17:31 UTC, AntoanRusinov commented on src/main/java/com/example/initial/entity/User.java
> +    @Column(name = "user-name", unique = true)
columns in database are ALWAYS with underscore, so this has to be user_name

2023-07-19 17:31 UTC, AntoanRusinov requested changes
small changes needed

2023-07-20 16:01 UTC, AntoanRusinov commented on src/main/java/com/example/initial/config/RabbitMQConfig.java
> +
we can talk about this next week, don't worry for now

2023-07-20 16:02 UTC, AntoanRusinov commented on src/main/java/com/example/initial/repository/UserRepository.java
> +
delete empty line here

2023-07-20 16:02 UTC, AntoanRusinov commented on src/main/java/com/example/initial/repository/UserRepository.java
> +
here also

2023-07-24 06:47 UTC, AntoanRusinov approved these changes
lgtm

2023-07-24 06:48 UTC, merged